### ISSUE TITLE
Error in "Article" example

### ISSUE THREAD

**Issue by riley-usagi** [JiriChara/vuex-crud#13]
`[Vue warn]: Error in created hook: "TypeError: Cannot read property 'params' of undefined"`

**Comment by riley-usagi** [comment]
"Article**s**" example works fine.

**Comment by JiriChara** [comment]
I am closing this, because it's obviously missing `vuex-router-sync`.

You can have a look in examples folder for full CRUD. It's also tested by nightwatch tests.
