### ISSUE TITLE
Best practice for error handling?

### ISSUE THREAD

**Issue by martinhbramwell** [JiriChara/vuex-crud#14]
Could you please create a documentation section about error handling?

In particular I need to know the best way to catch and handle an Authorization error?

I can call my store.dispatch('logIn') from each of the `onXXXError` handlers.  However, with my limited experience so far, I see no way to stop the error from surfacing in the user's browser log.

**Comment by k8n** [comment]
I am noting that vuex-crud calls error handlers from inside mutations (e.g. [onFetchListError](https://github.com/JiriChara/vuex-crud/blob/master/src/vuex-crud/createMutations.js#L54)).

As far as I understand it, dispatching actions from inside mutation goes against the [vuex design principle](https://stackoverflow.com/a/44309806/497988).

So, I imagine, the way one should handle errors is to catch them inside components that call upon the store. E.g.

```
this.$store.dispatch('foo/fetchList')
  .then(function() { /* ... */ })
  .catch(function(parsedError) { /* ... dispatch actions to handle errors ... */ })
```

**Comment by JiriChara** [comment]
Hey @martinhbramwell @k8n,

sorry for my late reply, but I was on holiday without my laptop :-).

`onFetchListError`, `onfetchListSuccess` are actually not meant to be an error handlers, but rather a simple callbacks to modify the store in a custom way.

And I agree with @k8n that you should handle errors using promises on your component level

**Comment by JiriChara** [comment]
I will update the documentation, so it's more clear that there should be no side-effects in `onFetchListError` callbacks

**Comment by martinhbramwell** [comment]
I am confused.

I took you example and replaced [the 'onFetchArticles()' lines](https://github.com/JiriChara/vuex-crud/blob/33a2fd47f51d31e9332c2544ca5d6d03db673d39/examples/blog/components/Blog.vue#L37) 

      onFetchArticles() {
        try {
          LG(' * * Try to fetch articles * *');
          this.fetchArticles();
        } catch (e) {
          LG(` * * * Blog :: onFetchArticles -- error ${e}`);
        }
      },

**Comment by martinhbramwell** [comment]
My requirements include keeping the user's browser console free of any errors or warnings.

I took [your example](https://github.com/JiriChara/vuex-crud/blob/33a2fd47f51d31e9332c2544ca5d6d03db673d39/examples/blog/components/Blog.vue#L37) and replaced those lines with

      onFetchArticles() {
        LG(' * * Try to fetch articles * *');
        this.fetchArticles()
          .then(() => { LG(' * * Fetched articles * *'); })
          .catch((e) => {
            LG(`*** Error while fetching articles :: ${e}***`);
          });
      },

When logged out and clicking `Fetch articles` I see : 
```
* * Try to fetch articles * *
GET ...myserver/api/articles 401 (Unauthorized) .   .   .   xhr.js?ec6c:178`
*** Error while fetching articles :: Error: Request failed with status code 401***`
```

Where **GET ...myserver/api/articles 401 (Unauthorized) .   .   .   xhr.js?ec6c:178** is a big red line!

How can I *completely* clean up the console?

**Comment by JiriChara** [comment]
@martinhbramwell I think those errors comes from default server logging see: https://github.com/axios/axios/issues/599

I am really not sure if we can do anything about it. :thinking:

**Comment by JiriChara** [comment]
Also: https://stackoverflow.com/questions/41515732/hide-401-console-error-in-chrome-dev-tools-getting-401-on-fetch-call

**Comment by martinhbramwell** [comment]
Right!  Understood. Thanks for looking into it and thanks for clarifying.
