### ISSUE TITLE
How to call getter from parseList()?

### ISSUE THREAD

**Issue by yourself-yourorg** [JiriChara/vuex-crud#15]
In my parseList I want to get an existing list from the store and merge newer values into it.

What is the correct way to access elements in the store while parsing the incoming response?

**Comment by JiriChara** [comment]
@yourself-yourorg `parseList` is used to modify your response from the server before it is going to the mutation. You can override `fetchListSuccess` mutation or create a new action and corresponding mutation

**Comment by yourself-yourorg** [comment]
Nice!  Thanks!
