### ISSUE TITLE
Created entry not being added to the list

### ISSUE THREAD

**Issue by sourenaraya** [JiriChara/vuex-crud#20]
I have list of todos, for example (rendered from todoList). On the same page i have form and button that adds a new todo. I expected this newborn todo being added to todoList (and rendered to the page), but thats not the case.
Is that bug or feature? I think there is some inconsistence, because deleted todo being deleted from todoList and page.

**Comment by JiriChara** [comment]
Hey @sourenaraya,

please have a look on: https://github.com/JiriChara/vuex-crud/issues/18
