### ISSUE TITLE
Related support

### ISSUE THREAD

**Issue by josx** [JiriChara/vuex-crud#4]
do you think is it worth it to have a related feature? 

Like getRelated('pages') --> calls API on articles/id/pages

if yes, how do you think we can do the state?

**Comment by JiriChara** [comment]
Hey @josx,

I am not a huge fan of nested resources I prefer to use filters in those cases like:

```
GET /pages?byArticle=1
```

You are not the only one who asked me about that feature, but some people also wanted to have event more nested resources: `libraries/:id/books/:id/pages/:id` and it can get complicated.

Redux/Vuex are not really good for dealing with nested resources. The workaround is to have normalized responses and then denormalize them in the view using library like: https://github.com/paularmstrong/normalizr. Managing the state is definitely possible, but i am not sure how to implement nested CRUD modules in nice and clean way.

Maybe something like (not quite sure yet though)

```js
import createCrudModule from 'vuex-crud';

const crudModule = createCrudModule({
  resource: 'articles',
  hasMany: 'pages'
});

crudModule.pages.fetchSingle({ id: 123 });
```

**Comment by josx** [comment]
The reference is [Redux-orm](https://github.com/tommikaikkonen/redux-orm) and for vuex exists [vuex-orm](https://github.com/revolver-app/vuex-orm) both  using normalizr

But vuex-orm is in the firsts versions and doesnt support many relations types, and also lacks of api population.

**Comment by JiriChara** [comment]
I definitely don't want to implement the full ORM, but I will try to come up with something simple though
