### ISSUE TITLE
 TypeError: data.forEach is not a function at Store.fetchListSuccess

### ISSUE THREAD

**Issue by kajcula** [JiriChara/vuex-crud#6]
I try fetchList from wordpress API custom navigation, but vuex crud return this error: 

> TypeError: data.forEach is not a function at Store.fetchListSuccess

What am I doing wrong? My JSON structure look like this: 
`[
    {
        "id": 2959,
        "name": "1_Websites",
        "slug": "1_websites",
        "description": "",
        "count": 4,
        "items": [
            {
                "id": 46783,
                "order": 1,
                "parent": 0,
                "title": "Blog",
                "url": "https://google.com",
                "attr": "",
                "target": "",
                "classes": "",
                "xfn": "",
                "description": "",
                "object_id": 46783,
                "object": "custom",
                "type": "custom",
                "type_label": "Custom Link",
                "object_slug": "blog"
            },
            {
                "id": 46779,
                "order": 2,
                "parent": 0,
                "title": "Kontakt",
                "url": "https://google.com/",
                "attr": "",
                "target": "",
                "classes": "",
                "xfn": "",
                "description": "",
                "object_id": 46779,
                "object": "custom",
                "type": "custom",
                "type_label": "Custom Link",
                "object_slug": "kontakt"
            },
            {
                "id": 46781,
                "order": 3,
                "parent": 0,
                "title": "Home",
                "url": "https://google.com/",
                "attr": "",
                "target": "",
                "classes": "",
                "xfn": "",
                "description": "",
                "object_id": 46781,
                "object": "custom",
                "type": "custom",
                "type_label": "Custom Link",
                "object_slug": "home"
            },
            {
                "id": 46782,
                "order": 4,
                "parent": 0,
                "title": "Ideas",
                "url": "https://google.com",
                "attr": "",
                "target": "",
                "classes": "",
                "xfn": "",
                "description": "",
                "object_id": 46782,
                "object": "custom",
                "type": "custom",
                "type_label": "Custom Link",
                "object_slug": "ideas"
            }
        ],
        "meta": {
            "links": {
                "collection": "https://google.com/",
                "self": "https://google.com"
            }
        }
    },
    {
        "id": 2957,
        "name": "2_Office",
        "slug": "2_office",
        "description": "",
        "count": 4,
        "items": [
            {
                "id": 46771,
                "order": 1,
                "parent": 0,
                "title": "Word",
                "url": "https://office.live.com/start/Word.aspx",
                "attr": "",
                "target": "",
                "classes": "",
                "xfn": "",
                "description": "",
                "object_id": 46771,
                "object": "custom",
                "type": "custom",
                "type_label": "Custom Link",
                "object_slug": "word"
            },
            {
                "id": 46772,
                "order": 2,
                "parent": 0,
                "title": "Excel",
                "url": "https://office.live.com/start/Excel.aspx",
                "attr": "",
                "target": "",
                "classes": "",
                "xfn": "",
                "description": "",
                "object_id": 46772,
                "object": "custom",
                "type": "custom",
                "type_label": "Custom Link",
                "object_slug": "excel"
            },
            {
                "id": 46773,
                "order": 3,
                "parent": 0,
                "title": "PowerPoint",
                "url": "https://office.live.com/start/PowerPoint.aspx",
                "attr": "",
                "target": "",
                "classes": "",
                "xfn": "",
                "description": "",
                "object_id": 46773,
                "object": "custom",
                "type": "custom",
                "type_label": "Custom Link",
                "object_slug": "powerpoint"
            },
            {
                "id": 46774,
                "order": 4,
                "parent": 0,
                "title": "OneNote",
                "url": "https://www.onenote.com/notebooks",
                "attr": "",
                "target": "",
                "classes": "",
                "xfn": "",
                "description": "",
                "object_id": 46774,
                "object": "custom",
                "type": "custom",
                "type_label": "Custom Link",
                "object_slug": "onenote"
            }
        ],
        "meta": {
            "links": {
                "collection": "https://google.com",
                "self": "https://google.com"
            }
        }
    }
]`

**Comment by JiriChara** [comment]
Hey @kajcula,

the JSON response looks alright. Can you please share with me actual code? The definition of you CRUD module and the way you fetch the list?

Can you also put a debugger breakpoint on this line: https://github.com/JiriChara/vuex-crud/blob/master/src/vuex-crud/createMutations.js#L39 and tell me what is the `response` and `state`?

Thanks

**Comment by kajcula** [comment]
I try this:
```
 async asyncData ({store}) {
     const menus = await store.dispatch('menus/fetchList')
     return { menus: menus }
    }
```
and that for layout page
```
methods: {
      ...mapActions("menus', {
        menus: 'fetchList"
      })
      fetchData () {
        return this.menus()
      }
    },
    created () {
      this.fetchData()
    }
```

and always `response` return ok

```
response:Object
    config:Object
    data:Array(10)
    headers:Object
    request:XMLHttpRequest
    status:200
    statusText:"OK"
```
and `state`

```
state:Object
    entities:Object
    fetchListError:null
    fetchSingleError:null
    isFetchingList:true
    isFetchingSingle:false
    list:Array(0)
    singles:Array(0)
```

**Comment by JiriChara** [comment]
That is strange it looks like `forEach` method is not defined on arrays. What browser are you using? It should be supported by every browser starting from IE 9 :thinking:. Do you use babel polyfill: https://babeljs.io/docs/usage/polyfill/?

Can you also go to console and simply add `[].forEach` and hit enter. Is that method defined?

**Comment by kajcula** [comment]
I use Google Chrome Version 58.0.3029.110 and I also install the newest nuxt 1.0.0-rc9. 
When I add to console `[].forEach` browser can see this method. 

I don't need yet babel-polyfill so I don't add it to the dependencies..

**Comment by JiriChara** [comment]
`[].forEach()` will not work, because you need to provide a callback method like: `[1,2,3].forEach(function (x) { console.log(x); });`, but it looks like it's not failing on the client side, but rather on server for some reason.

I have't tried vuex-crud in combination with nuxt, but I will give it a try. I am currently at work, but I will look into it asap. I think it has something to do with the babel configuration in nuxt.

**Comment by JiriChara** [comment]
What is your node.js version?

**Comment by kajcula** [comment]
Sorry.. you have right. forEach working correctly :) my mistake 

node.js `v6.11.2`, but I also use yarn with nuxt

**Comment by JiriChara** [comment]
It's very strange, because I was not able to reproduce it locally.

What I did was:

```js
// store/index.js
import Vuex from 'vuex'

import articles from './articles'

const createStore = () => {
  return new Vuex.Store({
    modules: {
      articles
    }
  })
}

export default createStore
```

```js
// store/articles.js
import createCRUDmodule from 'vuex-crud'

export default createCRUDmodule({
  resource: 'articles',

  urlRoot: 'http://localhost:3001/articles'
})
```

```html
<!-- pages/index.vue -->
<template>
  <div>
    {{ articles }}
  </div>
</template>

<script>

export default {
  async asyncData ({ store }) {
    const articles = await store.dispatch('articles/fetchList')

    return {
      articles: articles.data
    }
  }
}
</script>
```

and it displays the articles on the screen. Anyway I will try to implement a Nuxt way to create modules so you will be able to get rid of `store/index.js` file and just use `store/articles.js`

Maybe something like this:

```js
// store/articles.js
import createCRUDmodule from 'vuex-crud'

export default createCRUDmodule({
  resource: 'articles',

  urlRoot: 'http://localhost:3001/articles',

  nuxt: true
})
```

Can you also please try to edit your crud module to have a custom `parseList` method like this for example:

```js
import createCRUDmodule from 'vuex-crud'

export default createCRUDmodule({
  resource: 'menus',

  parseList(res) {
    return {
       ..res,
       data: [
         {
           id: 1,
           name: 'foo'
         },
         {
           id: 2,
           name: 'bar'
         }
       ]
    }
  }
})
```

and change your asyncData method to:

```js
async asyncData ({store}) {
  const menus = await store.dispatch('menus/fetchList').data
  return { menus }
}
```

**Comment by JiriChara** [comment]
If I change my module to:

```js
import createCRUDModule from 'vuex-crud'

const crudModule = createCRUDModule({
  resource: 'articles',

  urlRoot: 'http://localhost:3001/articles'
})

const state = () => crudModule.state

const { actions, mutations, getters } = crudModule

export {
  state,
  actions,
  mutations,
  getters
}
```

then it works without `store/index.js` file

**Comment by kajcula** [comment]
I found where was a problem. It was a problem not with vuex-crud but with Wordpress Rest API. JSON was Object with Objects but should be Array of Objects. Second thing is that Wordpress always return id key name like "ID" not "id". Thank you for your help!

**Comment by JiriChara** [comment]
Hey, glad to you have found it out :tada:. You can use `parseList` option in your crud module to transfer your response to array:

```js
import createCRUDModule from 'vuex-crud'

const crudModule = createCRUDModule({
  resource: 'menus',

  idAttribute: 'ID', // use ID as an attribute

  parseList(res) {
    const data = res.data;

    return Object.assign({}, res, {
      data: data.data // retrieve array from the json response
    });
  }
})

const state = () => crudModule.state

const { actions, mutations, getters } = crudModule

export {
  state,
  actions,
  mutations,
  getters
}
```
